language: node_js

node_js:
  - stable
  - lts/dubnium
  - lts/carbon
  - lts/boron

after_success:
  - npm install --global coveralls
  - ./node_modules/.bin/nyc report --reporter=text-lcov | coveralls
